# Generated by Django 6.0.6 on 2026-06-06 09:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('swimmers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Montag'), (1, 'Dienstag'), (2, 'Mittwoch'), (3, 'Donnerstag'), (4, 'Freitag'), (5, 'Samstag'), (6, 'Sonntag')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=200)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_sessions', to='groups.group')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExcuseToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('swimmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excuse_tokens', to='swimmers.swimmer')),
                ('recurring_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.recurringsession')),
            ],
            options={
                'unique_together': {('swimmer', 'recurring_session', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SessionException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(max_length=200)),
                ('affects_all', models.BooleanField(default=False, help_text='If true, cancels every recurring session on this date regardless of selection.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affected_sessions', models.ManyToManyField(blank=True, help_text='Leave empty to affect ALL sessions on this date.', related_name='exceptions', to='training.recurringsession')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='SessionInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('trainer_notes', models.TextField(blank=True, help_text='General notes for this session.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recurring_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='training.recurringsession')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('recurring_session', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TrainingPlanEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('category', models.CharField(choices=[('warmup', 'Aufwärmen'), ('main', 'Hauptteil'), ('cooldown', 'Abkühlen')], default='main', max_length=20)),
                ('description', models.TextField()),
                ('distance', models.CharField(blank=True, help_text='e.g. 4×50m', max_length=50)),
                ('intensity', models.CharField(blank=True, help_text='e.g. Zone 2, Sprint', max_length=50)),
                ('rest_seconds', models.PositiveSmallIntegerField(blank=True, help_text='Rest in seconds', null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_entries', to='training.sessioninstance')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Anwesend'), ('absent', 'Abwesend'), ('excused', 'Entschuldigt'), ('unknown', 'Unbekannt')], default='unknown', max_length=20)),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('swimmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='swimmers.swimmer')),
                ('excuse_token', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.excusetoken')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='training.sessioninstance')),
            ],
            options={
                'ordering': ['swimmer__last_name', 'swimmer__first_name'],
                'unique_together': {('session', 'swimmer')},
            },
        ),
    ]
