# Generated by Django 6.0.6 on 2026-06-08 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('type', models.CharField(choices=[('50m_Pool', '50m Schwimmbecken'), ('25m_Pool', '25m Schwimmbecken'), ('athletic', 'Sport Halle'), ('other', 'other')], max_length=10)),
                ('city', models.CharField(max_length=200)),
                ('postal_code', models.CharField(blank=True, max_length=5)),
                ('street_address', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['swimmer__groupmembership_set__role', 'swimmer__last_name', 'swimmer__first_name']},
        ),
        migrations.AlterField(
            model_name='recurringsession',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_sessions', to='training.location'),
        ),
    ]
