# Generated by Django 6.0.6 on 2026-06-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_location_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['swimmer__last_name', 'swimmer__first_name']},
        ),
        migrations.AlterField(
            model_name='trainingplanentry',
            name='intensity',
            field=models.CharField(blank=True, help_text='e.g. GA I, Sprint', max_length=50),
        ),
    ]
