# Generated by Django 6.0.6 on 2026-06-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplanentry',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo of a hand-written plan, e.g. taken poolside.', null=True, upload_to='training_plans/%Y/%m/'),
        ),
    ]
