# Generated by Django 6.0.6 on 2026-06-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_trainingplanentry_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionexception',
            name='end_date',
            field=models.DateField(blank=True, help_text='Optional last day of the exception (inclusive). Leave empty for a single-day exception.', null=True),
        ),
        migrations.AlterField(
            model_name='sessionexception',
            name='affected_sessions',
            field=models.ManyToManyField(blank=True, help_text='Leave empty to affect ALL sessions on this date / date range.', related_name='exceptions', to='training.recurringsession'),
        ),
        migrations.AlterField(
            model_name='sessionexception',
            name='date',
            field=models.DateField(help_text='First (or only) day of the exception.'),
        ),
    ]
